import type { Metadata } from "next";
import "./globals.css";
import poppins from "./Fonts/font";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased text-black w-screen overflow-x-hidden bg-white`}
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
